# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=clmundo
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: clmundo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A clmundo worker -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=clmundo
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A clmundo beat -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=clmundo
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - redis

volumes:
  postgres_data: