# Generated by Django 5.2.6 on 2025-09-05 21:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-reported_at']},
        ),
        migrations.AddField(
            model_name='incident',
            name='affected_passengers',
            field=models.IntegerField(default=1, help_text='Número de pasajeros afectados'),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('transport', 'Transporte'), ('accommodation', 'Alojamiento'), ('service_quality', 'Calidad de Servicio'), ('schedule', 'Horarios'), ('safety', 'Seguridad'), ('weather', 'Clima'), ('health', 'Salud'), ('documentation', 'Documentación'), ('communication', 'Comunicación'), ('other', 'Otros')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='customer_satisfaction',
            field=models.IntegerField(blank=True, help_text='Calificación del cliente (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='evidence_description',
            field=models.TextField(blank=True, help_text='Descripción de evidencias (fotos, videos)'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Cuándo ocurrió el incidente'),
        ),
        migrations.AddField(
            model_name='incident',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Notas internas del equipo'),
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(blank=True, help_text='Ubicación donde ocurrió el incidente', max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_contact',
            field=models.CharField(blank=True, help_text='Teléfono del reportero', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='requires_followup',
            field=models.BooleanField(default=False, help_text='Requiere seguimiento adicional'),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Abierta'), ('in_progress', 'En Progreso'), ('resolved', 'Resuelta'), ('closed', 'Cerrada')], default='open', max_length=15),
        ),
    ]
