# Generated by Django 5.2.6 on 2025-09-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_incident_options_incident_affected_passengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_notifications',
            field=models.BooleanField(default=True, help_text='Recibir notificaciones por WhatsApp'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_reminders',
            field=models.BooleanField(default=True, help_text='Recibir recordatorios por WhatsApp'),
        ),
        migrations.AddField(
            model_name='tripsegment',
            name='destination_latitude',
            field=models.FloatField(blank=True, help_text='Latitud destino', null=True),
        ),
        migrations.AddField(
            model_name='tripsegment',
            name='destination_longitude',
            field=models.FloatField(blank=True, help_text='Longitud destino', null=True),
        ),
        migrations.AddField(
            model_name='tripsegment',
            name='directions_distance',
            field=models.CharField(blank=True, help_text='Distancia estimada', max_length=50),
        ),
        migrations.AddField(
            model_name='tripsegment',
            name='directions_duration',
            field=models.CharField(blank=True, help_text='Duración estimada', max_length=50),
        ),
        migrations.AddField(
            model_name='tripsegment',
            name='last_directions_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripsegment',
            name='pickup_latitude',
            field=models.FloatField(blank=True, help_text='Latitud punto de encuentro', null=True),
        ),
        migrations.AddField(
            model_name='tripsegment',
            name='pickup_longitude',
            field=models.FloatField(blank=True, help_text='Longitud punto de encuentro', null=True),
        ),
    ]
